### PR TITLE
Add missing rospack dependency

### PR DESCRIPTION
**Pull request by paulbovbel**
Needed for roscd and rosrun at the very least.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Thank you for the patch.

**Comment by gavanderhoorn** [comment]
@dirk-thomas: would it be possible to get this released into Kinetic? Or the change backported? According to [status_page/ros_kinetic_default](http://repositories.ros.org/status_page/ros_kinetic_default.html?q=rosbash) the latest version of `rosbash` for Kinetic is `1.14.4` which doesn't seem to include this change.

I have a few environments which start from scratch and they're showing `rospack: no such command or filename` errors without this.

**Comment by dirk-thomas** [comment]
Released version 1.14.6 into Kinetic: ros/rosdistro/pull/21494

**Comment by gavanderhoorn** [comment]
Thanks. This simplifies things significantly.

**Pull request merged**
