### PR TITLE
Updated XMLTestResult class to provide text output simultaneously

### LINKED ISSUE #110: rosunit should allow simultaneous XML output and text output
Right now we are executing unit tests using make test in our buildfarm. 

Fixing an unexpected failure or a crash on a unit test in the buildfarm is an almost impossible task since we have no logs and the XML output only reports a crash and zero useful logs.

Example of XML output on the case of a crash:

> test [serial_driver_test] did not generate test results
>   File "/usr/lib/python2.7/unittest/case.py", line 331, in run
>     testMethod()
>   File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/runner.py", line 164, in fn
>     self.assert_(os.path.isfile(test_file), "test [%s] did not generate test results"%test_name)
>   File "/usr/lib/python2.7/unittest/case.py", line 424, in assertTrue
>     raise self.failureException(msg)

It would be very helpful to have alll std output as part of the XML report, if it cannot be made visible in the terminal running the tests.

### PR DESCRIPTION
**Pull request by talhaHavadar**
This commit should resolve #110. But it needs to be tested well since I couldn't test it deeply.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
The patch currently fails some of the tests. Please update it to at least pass the current testsuite.

**Comment by dirk-thomas** [comment]
The `lunar-devel` branch has been reintegrated into the `kinetic-devel` branch which automatically closed this PR. Please consider to create a new PR addressing the comments targeting the `kinetic-devel` branch instead. I am sorry for the inconvenience.

**Comment by talhaHavadar** [comment]
No problem I was facing with problems to run tests its probably related with my local env. I will create a new pr as soon as I fixed the issue.

**Comment by v-lopez** [comment]
@talhaHavadar Any updates on this? Are you looking into fixing the issues, or should I?

**Comment by talhaHavadar** [comment]
Of course you can continue on if you have time. I preferred to change _XMLTestResult's super class to unittest.TextTestResult so we can write test results to console in the same time. I am stuck currently, I couldnt test my code.

**Pull request closed without merging**
