### PR TITLE
Reuse previous results for better performance (replaces #97)

### PR DESCRIPTION
**Pull request by gerkey**
See ros/rospack#54

### CODE REVIEW

**Comment by wjwwood** [comment]
#97 (issues don't link from issue titles)

**Comment by rhaschke** [comment]
Due to @gerkey's rebase, the original changes are not directly associated to me anymore. 
Same applies for [rospack#54](https://github.com/ros/rospack/pull/54) / [#49](https://github.com/ros/rospack/pull/49). Is this intended?

**Comment by gerkey** [comment]
@rhaschke Nothing intended by the way that I structured the changes. Probably just my poor git/github workflow skills. What's the right way to assemble things? Feel free to do it a different way (e.g., take the changes I made back into your branch) and then we'll proceed with your PR.

**Comment by dirk-thomas** [comment]
Since this change relies on changes to rospack it must specify the upcoming rospack release as a minimum version for the dependency.

**Comment by rhaschke** [comment]
@gerkey I rebased the changes from your [rospack PR #54](https://github.com/ros/rospack/pull/54) onto [rospack #49](https://github.com/ros/rospack/pull/49) ([see here](https://github.com/ros/rospack/pull/49#issuecomment-163711308)). I suggest to close [rospack PR #54] and continue with the original [rospack #49](https://github.com/ros/rospack/pull/49).
The same applies here. #98 should be closed in favour of the original #97.

**Comment by gerkey** [comment]
Closing in favor of #97

**Pull request closed without merging**
