### PR TITLE
fixed wrong spelled words

### PR DESCRIPTION
**Pull request by freddii**

### CODE REVIEW

**Review by hidmic — COMMENTED** [review]
LGTM, though I wonder why your head repository shows up as unknown.

Also, @sloretz is there any other CI we should run for Noetic?

**Comment by freddii** [comment]
deleted my repo. thats why it is unknown.

**Comment by sloretz** [comment]
> Also, @sloretz is there any other CI we should run for Noetic?

Nope, PR jobs are good enough!

**Review by sloretz — APPROVED** [review]

**Review by jacobperron — APPROVED** [review]

**Comment by hidmic** [comment]
Alright then !

**Pull request merged**
