### PR TITLE
Adding support for fish shell

### PR DESCRIPTION
**Pull request by aclough**
This adds a rosfish alongside rosbash and the others to provide shell
functions such as roscd and appropriate tab completions.  Due to
differing syntax fish users will have to set environemnt variables
manually that are set by setup.sh for bash and zsh but once that is done
they should be able to use all the same facilities as other supported
shells.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Replaces #75.

Next time you can simply force push the squashed commit to the same branch the PR is made from. It will update automatically.

**Comment by ruffsl** [comment]
Can this be cherry-pick'ed into indigo-devel? As a fish shell user, it'd be nice to see this in the current LTS.

**Comment by dirk-thomas** [comment]
I  cherry-picked the commit (2901e4a3401e62b48c8dc1282947cdf401deb529) but it will likely take quite a while until it will be available from Debian since this repo was recently released into Indigo and no important fixes are pending atm. This change alone doesn't justify a new release (which will imply a rebuild of all downstream packages on the farm and a redownload of all downstream packages by users). Also the next LTS is already close (May 2016).

**Comment by ruffsl** [comment]
Understood, thanks dirk-thomas and aclough.

**Pull request merged**
