### PR TITLE
zshcompletion add trailing := to roslaunch args:=value completion

### PR DESCRIPTION
**Pull request by pseyfert**
(I'm very new to ros, please check if this introduces undesired effects)

The help message of `roslaunch` says

```
roslaunch -h
Usage: roslaunch [options] [package] <filename> [arg_name:=value...]
       roslaunch [options] <filename> [<filename>...] [arg_name:=value...]

If <filename> is a single dash ('-'), launch XML is read from standard input.

Options:
...
```

So far the roslaunch completion in zsh completes `arg_names`. As far as I understand, these will always be trailed with `:=`. This change adds the trailing `:=` after argument names.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Thanks for the creating the PR.

> please check if this introduces undesired effects

Please do some amount of testing yourself and also post the commands you tried before as well as after the patch including the behavior you get.

**Comment by dirk-thomas** [comment]
@pseyfert Friendly ping.

**Comment by pseyfert** [comment]
hi,

comparison

old
```
roslaunch <ourpackage> <ourapplication> rosbag_⇥
roslaunch <ourpackage> <ourapplication> rosbag_name␣
```
new
```
roslaunch <ourpackage> <ourapplication> rosbag_⇥
roslaunch <ourpackage> <ourapplication> rosbag_name:=
```

other completions
```
cd ⇥
```
suggests a list of all local directories (before and after, unchanged)

```
rosbag record ⇥
```
w/o running roscore inserts a space (before and after, unchanged)

```
rostopic ⇥
bw    echo  find  hz    info  list  pub   type
```
before and after, unchanged

```
rostest ⇥
```
suggests packages (before and after, unchanged)
```
rostest <ourpackage> ⇥
```
suggests applications (before and after, unchanged)
```
rostest <ourpackage> <ourapplication> ⇥
```
suggests local files and directories (before and after, unchanged)

```
roslaunch -⇥
```
doesn't suggest anything (before and after, unchanged)

**Comment by dirk-thomas** [comment]
Thanks for the improvement.

**Pull request merged**
