### PR TITLE
use platform dependent argument for 'find -perm' (fix #33)

### LINKED ISSUE #33: Deprecated use of "find"
rosbash uses "+111" as a -perm argument to find, and I'm pretty sure +111 is used in a few other places as well.

Using "+" in perm has been deprecated in find for over 8 years, and was completely removed in new versions of find. (see man find)

This causes rosrun to not function AT ALL in Fedora 19+.

Might I suggest using "-111" instead?

### PR DESCRIPTION
**Pull request by dirk-thomas**
@cottsay @wjwwood Please review

### CODE REVIEW

**Comment by wjwwood** [comment]
+1

**Comment by wjwwood** [comment]
I tried it locally.

**Comment by cottsay** [comment]
This is great, thanks so much. Any chance this can make it into Groovy?

**Comment by dirk-thomas** [comment]
Yes, will be backported after the merge.

**Comment by cottsay** [comment]
Thank you!

**Pull request merged**
