### PR TITLE
add rosconsole tab completion for bash

### PR DESCRIPTION
**Pull request by cmansley**

### CODE REVIEW

**Comment by wjwwood** [comment]
Looks reasonable to me, but I didn't try it out yet.

**Comment by cmansley** [comment]
In trying it, I found a bug in rosconsole. See ros/ros_comm#631 But, the auto-complete works as expected.

**Comment by dirk-thomas** [comment]
I just tried the patch and the completion itself looks good.

I ran into this but I don't recall what exactly I did:

```
Traceback (most recent call last):
  File "/home/dthomas/ros/indigo/ros_core/devel/bin/rosconsole", line 6, in <module>
    exec(fh.read())
  File "<string>", line 3, in <module>
  File "/home/dthomas/ros/indigo/ros_core/src/ros_comm/clients/rospy/src/rospy/rosconsole.py", line 165, in main
    _rosconsole_cmd_get(argv)
  File "/home/dthomas/ros/indigo/ros_core/src/ros_comm/clients/rospy/src/rospy/rosconsole.py", line 130, in _rosconsole_cmd_get
    if args[1] not in logger_level._current_levels:
AttributeError: 'LoggerLevelServiceCaller' object has no attribute '_current_levels'
```

Looking at the code it seems like `LoggerLevelServiceCaller` does not define any member variable in the constructor: https://github.com/ros/ros_comm/blob/134adfabc439cc006bed964697750802fcc36411/clients/rospy/src/rospy/logger_level_service_caller.py#L55

But the line at raises does use a member directly after instantiating the class.

Can you look into this and propose a fix? Eventually adding the following to the constructor is enough but I am not sure:

```
self._current_loggers = []
self._current_levels = {}
```

**Comment by cmansley** [comment]
Please read the previous comments. I already tagged this issue and submitted a pull request. ros/ros_comm#631

**Comment by dirk-thomas** [comment]
Sorry, I missed the referenced PR. (Still it looks fragile to not create member variables in the constructor if they are used outside.)

Can you please squash the two commits please. I will then merge it into jade and cherry-pick it to indigo.

**Comment by cmansley** [comment]
I squashed down the commits. It should be ready for merge. Thanks!

**Comment by dirk-thomas** [comment]
Thanks. Cherry picked to indigo branch: c3825b4b8deaf4296099c33f33d22691ce91e385

**Pull request merged**
