### PR TITLE
Added new function roscpd to address issue #145

### PR DESCRIPTION
**Pull request by dharapatel1596**
A new ros function "roscpd" is added whose functionalities are as follows:

- Copy a directory (inside or outside catkin workspace) **recursively** with all files and folders to a target location.
- Copy a single file (inside or outside catkin workspace) to a target location. 

This functionality is added to address the issue #145.

### CODE REVIEW

**Review by hidmic — COMMENTED** [review]
I'm not sure I follow how this patch addresses #145. 

Correct me if I'm wrong, but adapting the repro given there:

```
roscpd roscpp_tutorials TwoInts.h .
```

would result in the third argument being ignored and an attempt to recursively copy some local `roscpp_tutorials` directory into a `TwoInts.h` directory.

I think you may want to revisit the discussion on #145.

**Comment by dharapatel1596** [comment]
So according to what I followed from the discussion is that: the command 'roscp' looks for the file only in the specified package and if the file is not present there it will result into one or the other error.

So, I tried to introduce a new command 'roscpd' which can now look for the files and directories both **inside catkin workspace** or also **outside catkin workspace**. 

If you look at the help of the command 'roscpd', it does not take three arguments. 
So testing the command with:

`roscpd roscpp_tutorials TwoInts.h .`

will result into showing the help of the command.

With this command now, package name is not required. I tried to keep the command short. 

Let me present an example of testing above command:

`roscpd src/roscpp_tutorial/<filename> .`

will copy the **provided file** to the **current location**.

`roscpd src/roscpp_tutorial/ .` 

will copy the package **roscpp_tutorial** to the **current directory**. 

So, instead of restricting the search into a package, I made it like, looking for the file into a directory path provided. This directory path can be **relative** as well as **absolute** from the current location. 

Hence, user now has an option to copy a file even if it is not located into the package and hence, enabling the user to copy it from anywhere in the system to the target location. 

I think this resolves the issue. 

Let me know what you think.

**Comment by hidmic** [comment]
Hmm, `roscp`'s raison d'être is to not have to fiddle with package paths. As-is, `roscpd` is just an alias for `cp -r`.

IIUC #145 is about adding other search paths to `roscp` so it can find files that are outside a package's share directory (which may or may not be possible depending on the install space layout). PTAL @ #145.

**Comment by dharapatel1596** [comment]
Okay. So command `roscpd` is not resolving the Issue #145. But can we go ahead with introducing `roscpd` as the new command, for copying the directory/file from anywhere to the target location?

**Comment by hidmic** [comment]
> But can we go ahead with introducing roscpd as the new command, for copying the directory/file from anywhere to the target location?

I'm reluctant to introduce an alias for `cp`. Why not just use `cp`? But I'll let @jacobperron chime in too.

**Comment by jacobperron** [comment]
I have similar feelings as @hidmic. `ros*` commands exist to operate on ROS-aware install/build prefixes. As pointed out, the proposed `roscpd` is simply an alias for `cp -r`. I.e. What advantage does `roscpd` have over running `cp -r`?

**Comment by dharapatel1596** [comment]
As there is not much advantage of `roscpd` over `cp -r` .
It is more or less same. I was trying to give abstraction with ROS command. I agree with your point too.

**Comment by jacobperron** [comment]
> As there is not much advantage of roscpd over cp -r .
It is more or less same. I was trying to give abstraction with ROS command. I agree with your point too.

On the premise that this PR is not adding much value, I'm inclined to close this this ticket.

**Pull request closed without merging**
