### PR TITLE
rostopic autocompletion for published topics, msg-type and YAML

### PR DESCRIPTION
**Pull request by bajo**
This should fix parts of issue #48 rosbash: zsh auto-completion issues

### CODE REVIEW

**Comment by dirk-thomas** [comment]
@wjwwood can you please try this on OSX?

**Comment by wjwwood** [comment]
Working on it.

**Comment by wjwwood** [comment]
@bajo what is the expected behavior before and after this patch? I am able to tab complete on zsh on my mac, but I'm not sure what exactly I am looking for.

**Comment by wjwwood** [comment]
I will say the tab completion does look better, I just wanted a more exact list of things you expect to be fixed by this.

**Comment by bajo** [comment]
@wjwwood Before the patch, at least on my machine, the tab completion did not work for the topic name, the msg-type and the data in yaml format. If you want to send a message with a type like geometry_msgs/PoseWithCovarianceStamped you need to type all the fields and the data by hand and watch out for problems with the format and escaping of data, which is kind of annoying. :)

After the patch the tab completion should be able to complete the topic name, based on the already available topics. The type of the topic is retrieved and completed, so no std_msgs/String publishing on a topic which expects something like a geometry_msgs/PoseStamped and the prototype of the message is also completed. In the prototype you can just fill in the parts of data you want to publish.

**Comment by dirk-thomas** [comment]
Thanks for clarifying. The patch looks good.

There is one more command completion in #48 which does not yet work completely in zsh: `rosrun` Could I convince you to also provide a pull request for that? :wink:

**Comment by wjwwood** [comment]
+1 from me, that is what I observed, but I just wanted to make sure you didn't fix anything else I should test too.

Thanks for this!

**Comment by bajo** [comment]
I'll have a look at that problem as well, after my weekend trip. ;)

**Pull request merged**
